---
- name: Install Cinder packages
  apt:
    name:
      - cinder-api
      - cinder-scheduler
    state: present

- name: Configure Cinder
  blockinfile:
    path: /etc/cinder/cinder.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- cinder.conf"
    block: |
      [database]
      connection = mysql+pymysql://cinder:CINDER_DBPASS@controller/cinder

      [DEFAULT]
      transport_url = rabbit://openstack:RABBIT_PASS@controller
      auth_strategy = keystone

      [keystone_authtoken]
      www_authenticate_uri = http://controller:5000
      auth_url = http://controller:5000
      memcached_servers = controller:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = cinder
      password = CINDER_PASS

      my_ip = 10.0.0.11

      [oslo_concurrency]
      lock_path = /var/lib/cinder/tmp
  notify:
    - restart cinder-api

- name: Populate Block Storage database
  become: true
  command: >
    cinder-manage db sync

- name: Configure Compute to use Block Storage
  blockinfile:
    path: /etc/nova/nova.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- nova.conf"
    block: |
      [cinder]
      os_region_name = RegionOne
  notify:
    - restart nova-api

